FROM confluentinc/cp-kafka-connect:7.6.1

USER root

RUN yum install -y unzip wget && yum clean all

RUN mkdir -p /usr/share/confluent-hub-components/debezium-postgres

RUN wget -O /tmp/debezium-postgres.zip \
https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/2.7.0.Final/debezium-connector-postgres-2.7.0.Final-plugin.zip \
&& unzip /tmp/debezium-postgres.zip \
-d /usr/share/confluent-hub-components/debezium-postgres \
&& rm -f /tmp/debezium-postgres.zip

ENV CONNECT_PLUGIN_PATH="/usr/share/java,/usr/share/confluent-hub-components"

USER appuser